# Generated by Django 6.0.6 on 2026-06-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjengoapp', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='escrow_status',
            field=models.CharField(choices=[('held', 'Held'), ('released', 'Released')], default='held', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
