# Generated by Django 6.0.6 on 2026-06-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjengoapp', '0006_payment_escrow_status_payment_released_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
