# Generated by Django 6.0.6 on 2026-06-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjengoapp', '0007_workerprofile_mpesa_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='payment_received',
            field=models.BooleanField(default=False),
        ),
    ]
