# Generated by Django 6.0.6 on 2026-07-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjengoapp', '0011_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='preferred_contact',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
