from django.urls import path
from .views import (
    CustomerProfileDetailView,
    CustomerProfileListCreateView,
    JobDetailView,
    JobListCreateView,
    MessageDetailView,
    MessageListCreateView,
    MpesaCallbackView,
    NotificationDetailView,
    NotificationListCreateView,
    PaymentDetailView,
    PaymentListCreateView,
    PortfolioDetailView,
    PortfolioListCreateView,
    ProgressUpdateDetailView,
    ProgressUpdateListCreateView,
    ProjectDetailView,
    ProjectListCreateView,
    QuotationDetailView,
    QuotationListCreateView,
    ReviewDetailView,
    ReviewListCreateView,
    StkPushView,
    UserRegistrationView,
    WorkerProfileDetailView,
    WorkerProfileListCreateView,
    AcceptQuotationView,
    RejectQuotationView,
    UserListView,
)

urlpatterns = [
    path('signup/', UserRegistrationView.as_view(), name='signup'),
    path('create-user/', UserRegistrationView.as_view(), name='create-user'),
    path('users/', UserListView.as_view(), name='users'),
    path('jobs/', JobListCreateView.as_view(), name='jobs'),
    path('jobs/<int:pk>/', JobDetailView.as_view(), name='job-detail'),
    path('workerprofile/', WorkerProfileListCreateView.as_view(), name='workerprofile'),
    path('workerprofile/<int:pk>/', WorkerProfileDetailView.as_view(), name='workerprofile-detail'),
    path('customerprofile/', CustomerProfileListCreateView.as_view(), name='customerprofile'),
    path('customerprofile/<int:pk>/', CustomerProfileDetailView.as_view(), name='customerprofile-detail'),
    path('quotations/', QuotationListCreateView.as_view(), name='quotations'),
    path('quotations/<int:pk>/', QuotationDetailView.as_view(), name='quotation-detail'),
    path('projects/', ProjectListCreateView.as_view(), name='projects'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('payments/', PaymentListCreateView.as_view(), name='payments'),
    path('payments/<int:pk>/', PaymentDetailView.as_view(), name='payment-detail'),
    path('payments/stk-push/', StkPushView.as_view(), name='payment-stk-push'),
    path('payments/callback/', MpesaCallbackView.as_view(), name='payment-callback'),
    path('progress-updates/', ProgressUpdateListCreateView.as_view(), name='progress-updates'),
    path('progress-updates/<int:pk>/', ProgressUpdateDetailView.as_view(), name='progress-update-detail'),
    path('reviews/', ReviewListCreateView.as_view(), name='reviews'),
    path('reviews/<int:pk>/', ReviewDetailView.as_view(), name='review-detail'),
    path('portfolios/', PortfolioListCreateView.as_view(), name='portfolios'),
    path('portfolios/<int:pk>/', PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('messages/', MessageListCreateView.as_view(), name='messages'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message-detail'),
    path('notifications/', NotificationListCreateView.as_view(), name='notifications'),
    path('notifications/<int:pk>/', NotificationDetailView.as_view(), name='notification-detail'),
    path('quotations/<int:quotation_id>/accept/',AcceptQuotationView.as_view(),name='accept-quotation'),
    path('quotations/<int:quotation_id>/reject/',RejectQuotationView.as_view(),name='reject-quotation'),
]
