from django.urls import path
from .views import (
    CustomerProfileDetailView,
    CustomerProfileListCreateView,
    JobDetailView,
    JobListCreateView,
    MessageDetailView,
    MessageListCreateView,
    NotificationDetailView,
    NotificationListCreateView,
    PortfolioDetailView,
    PortfolioListCreateView,
    ProjectDetailView,
    ProjectListCreateView,
    QuotationDetailView,
    QuotationListCreateView,
    ReviewDetailView,
    ReviewListCreateView,
    WorkerProfileDetailView,
    WorkerProfileListCreateView,
)

urlpatterns = [
    path('jobs/', JobListCreateView.as_view(), name='jobs'),
    path('jobs/<int:pk>/', JobDetailView.as_view(), name='job-detail'),
    path('workerprofile/', WorkerProfileListCreateView.as_view(), name='workerprofile'),
    path('workerprofile/<int:pk>/', WorkerProfileDetailView.as_view(), name='workerprofile-detail'),
        path('customerprofile/', CustomerProfileListCreateView.as_view(), name='customerprofile'),
    path('customerprofile/<int:pk>/', CustomerProfileDetailView.as_view(), name='customerprofile-detail'),
    path('quotations/', QuotationListCreateView.as_view(), name='quotations'),
    path('quotations/<int:pk>/', QuotationDetailView.as_view(), name='quotation-detail'),
    path('projects/', ProjectListCreateView.as_view(), name='projects'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('reviews/', ReviewListCreateView.as_view(), name='reviews'),
    path('reviews/<int:pk>/', ReviewDetailView.as_view(), name='review-detail'),
    path('portfolios/', PortfolioListCreateView.as_view(), name='portfolios'),
    path('portfolios/<int:pk>/', PortfolioDetailView.as_view(), name='portfolio-detail'),
    path('messages/', MessageListCreateView.as_view(), name='messages'),
    path('messages/<int:pk>/', MessageDetailView.as_view(), name='message-detail'),
    path('notifications/', NotificationListCreateView.as_view(), name='notifications'),
    path('notifications/<int:pk>/', NotificationDetailView.as_view(), name='notification-detail'),
]